
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    flyway:
      locations: classpath:db/migration
      baseline-on-migrate: true