CREATE TABLE character (
  character_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   other_names VARCHAR(255),
   gender VARCHAR(255),
   description VARCHAR(1000),
   image VARCHAR(255),
   CONSTRAINT pk_character PRIMARY KEY (character_id)
);